In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import pickle
from sklearn import svm
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import euclidean_distances
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score


F:\Users\jjoth\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [2]:
data = pd.read_csv('cleanedtrain2.csv', delimiter=',')
data.dropna(axis=0, how='any', thresh=None, subset=None, inplace=True)
data1 = data

F:\Users\jjoth\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (0,1,2) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
data2 = pd.read_csv('cleanedvalidation2.csv', delimiter=',')
data2.dropna(axis=0, how='any', thresh=None, subset=None, inplace=True)
data3 = data2

In [4]:

encoder = preprocessing.LabelEncoder()
label = encoder.fit_transform(data1['label'])
print(label)
print(len(label))

[2 2 2 ... 1 1 1]
192151


In [5]:

encoder1 = preprocessing.LabelEncoder()
label1 = encoder.fit_transform(data3['label'])
print(label1)
print(len(label1))

[2 2 2 ... 1 1 1]
64053


In [6]:
d = np.load('test3.npy')
e = np.load('test4.npy')

f = np.concatenate((d,e),axis=1)


In [7]:
d.shape


(192151, 512)

In [8]:
f.shape

(192151, 1024)

In [9]:
d1 = np.load('valid1.npy')
e1 = np.load('valid2.npy')

f1 = np.concatenate((d1,e1),axis=1)
print(len(f1))

64053


In [10]:
#model fitting
#Import Gaussian Naive Bayes model
#from sklearn.naive_bayes import GaussianNB
#Create a Gaussian Classifier
#model = GaussianNB()
# Train the model using the training sets
#model.fit(f,label)


In [11]:
#saving the model
#filename = 'gaussian.sav'
#pickle.dump(model, open(filename, 'wb'))

In [12]:
filename = 'gaussian.sav'
model = pickle.load(open(filename, 'rb'))

In [13]:
predicted1=model.predict(f1)

In [14]:
result1 = (accuracy_score(predicted1, label1)*100)
print(result1)

41.47815090628074


In [15]:
f1_score(label1, predicted1,average='weighted')

0.4381899446573546

In [16]:
#model training
#from sklearn.linear_model import LogisticRegression
#model1 = LogisticRegression(C=1e20)
#model1.fit(f, label)

In [17]:
#saving the model
#filename = 'logisticregression.sav'
#pickle.dump(model1, open(filename, 'wb'))

In [18]:
filename = 'logisticregression.sav'
model1 = pickle.load(open(filename, 'rb'))

In [19]:

preds12 = model1.predict(f1)

In [20]:

result = (accuracy_score(label1, preds12)*100)
print(result)

70.27461633334894


In [21]:
f1_score(label1, preds12,average='weighted')

0.66184717493055

In [22]:
#training randomforestclassifier
#from sklearn.ensemble import RandomForestClassifier
#clf = RandomForestClassifier(n_estimators = 100)
#clf.fit(f,label)

In [23]:
#saving the model
#filename = 'randomforest.sav'
#pickle.dump(clf, open(filename, 'wb'))

In [24]:
filename = 'randomforest.sav'
clf = pickle.load(open(filename, 'rb'))

In [25]:
preds22=clf.predict(f1)

In [26]:

result = (accuracy_score(label1, preds22)*100)
print(result)

81.66518351989758


In [27]:
f1_score(label1, preds22,average='weighted')

0.7954751685679046

In [28]:
#model creation
#model5 = XGBClassifier()
#model5.fit(f,label)
#filename = 'xdboost.sav'
#pickle.dump(model5, open(filename, 'wb'))

In [29]:
#ada=AdaBoostClassifier()


In [30]:
#ada.fit(f,label)

In [31]:
#filename = 'ada.sav'
#pickle.dump(ada, open(filename, 'wb'))

In [32]:
filename = 'ada.sav'
ada = pickle.load(open(filename, 'rb'))

In [33]:
pred12345=ada.predict(f1)

In [35]:
result = (accuracy_score(label1,pred12345 )*100)
print(result)

63.046227342981595


In [36]:
f1_score(label1, pred12345,average='weighted')

0.6160548655468113

In [37]:
from sklearn.tree import DecisionTreeClassifier
clf_gini = DecisionTreeClassifier(criterion = "gini",
            random_state = 100,max_depth=3, min_samples_leaf=5)
clf_gini.fit(f, label)
p = clf_gini.predict(f1)


In [38]:
print("Accuracy:",accuracy_score(label1, p)*100)
print("F1 score:",f1_score(label1, p,average='weighted'))

Accuracy: 68.40429019718046
F1 score: 0.5557040039658586


F:\Users\jjoth\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [39]:
data5 = pd.read_csv('cleanedtesting3.csv', delimiter=',')

In [40]:
data5.dropna(axis=0, how='any', thresh=None, subset=None, inplace=True)
data6 = data5

In [41]:
d2 = np.load('valid1.npy')
e2 = np.load('valid2.npy')
f2=np.concatenate((d2,e2),axis=1)

In [44]:
preds234=clf.predict(f2)

In [45]:
preds234

array([2, 2, 2, ..., 1, 2, 2], dtype=int64)

In [46]:
l12 = list(encoder.inverse_transform(preds234))

F:\Users\jjoth\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [47]:
l12

['unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'agreed',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelated',
 'unrelat

In [48]:
l13 = list(data5['id'])

In [49]:
l11 = list(zip(l13, l12))

In [50]:
df5 = pd.DataFrame(l11, columns=['id','label'])
df5.to_csv('submission.csv', encoding='utf-8', index=False)